import { Course, Announcement, Material, Activity, EnrolledProgram, CalendarEvent } from './types';

export const INITIAL_PROGRAM: EnrolledProgram = {
  programName: 'Bachelor of Science in Information Technology',
  degree: 'Undergraduate Program',
  department: 'College of Information and Digital Sciences',
  studentId: '2024-08912',
  studentName: 'Hazel Jane C. Cabanting',
  studentEmail: 'hazel.cabanting@school.edu',
  section: 'IT3B',
  academicYear: '2026-2027',
  semester: 'First Semester',
  totalCredits: 15,
  currentGpa: '3.88',
};

export const INITIAL_COURSES: Course[] = [
  {
    id: 'c1',
    name: 'Web Systems and Technologies',
    code: 'IT 634',
    section: 'Section IT3B',
    professor: 'Engr. Sofia Reyes',
    professorEmail: 's.reyes@school.edu',
    room: 'CIDS Building Lab 301',
    schedule: 'Mon, Wed • 7:30 AM - 9:00 AM',
    credits: 3,
    theme: 'bg-cyan-600',
    headerColor: '#0891b2',
    accentColor: 'text-cyan-600',
    grade: 'No data',
  },
  {
    id: 'c2',
    name: 'Internet of Things (IoT)',
    code: 'ITEL 602',
    section: 'Section IT3B',
    professor: 'Prof. Kevin Ashton',
    professorEmail: 'k.ashton@school.edu',
    room: 'Embedded Systems Lab 201',
    schedule: 'Tue, Thu • 10:00 AM - 12:00 PM',
    credits: 3,
    theme: 'bg-emerald-700',
    headerColor: '#047857',
    accentColor: 'text-emerald-700',
    grade: 'No data',
  },
  {
    id: 'c3',
    name: 'Artificial Intelligence',
    code: 'ITEL 601',
    section: 'Section IT3B',
    professor: 'Dr. Geoffrey Hinton',
    professorEmail: 'g.hinton@school.edu',
    room: 'CIDS Building Lab 402',
    schedule: 'Mon, Wed • 9:00 AM - 10:30 AM',
    credits: 3,
    theme: 'bg-blue-600',
    headerColor: '#1d4ed8',
    accentColor: 'text-blue-600',
    grade: 'No data',
  },
  {
    id: 'c4',
    name: 'Human-Computer Interaction 1',
    code: 'IT 635',
    section: 'Section IT3B',
    professor: 'Dr. Don Norman',
    professorEmail: 'd.norman@school.edu',
    room: 'Design & Media Lab 204',
    schedule: 'Fri • 9:00 AM - 12:00 PM',
    credits: 3,
    theme: 'bg-rose-600',
    headerColor: '#e11d48',
    accentColor: 'text-rose-600',
    grade: 'No data',
  },
  {
    id: 'c5',
    name: 'System Analysis and Design',
    code: 'IT 633',
    section: 'Section IT3A',
    isIrregular: true,
    sectionNote: 'Irregular Enrollment (Cross-enrolled with Section A)',
    professor: 'Dr. Larry Constantine',
    professorEmail: 'l.constantine@school.edu',
    room: 'Innovation Wing 305',
    schedule: 'Mon, Wed • 1:00 PM - 2:30 PM',
    credits: 3,
    theme: 'bg-orange-600',
    headerColor: '#ea580c',
    accentColor: 'text-orange-600',
    grade: 'No data',
  },
  {
    id: 'c6',
    name: 'System Integration and Architecture I',
    code: 'IT 632',
    section: 'Section IT3B',
    professor: 'Engr. Marcus Vance',
    professorEmail: 'm.vance@school.edu',
    room: 'Software Engineering Lab 102',
    schedule: 'Tue, Thu • 1:30 PM - 3:30 PM',
    credits: 3,
    theme: 'bg-purple-700',
    headerColor: '#7e22ce',
    accentColor: 'text-purple-700',
    grade: 'No data',
  },
  {
    id: 'c7',
    name: 'Integrative Programming and Technologies I',
    code: 'IT 631',
    section: 'Section IT3B',
    professor: 'Prof. Lena Torres',
    professorEmail: 'l.torres@school.edu',
    room: 'Software Engineering Lab 103',
    schedule: 'Tue, Thu • 3:30 PM - 5:30 PM',
    credits: 3,
    theme: 'bg-violet-600',
    headerColor: '#7c3aed',
    accentColor: 'text-violet-600',
    grade: 'No data',
  },
];

export const ARCHIVED_COURSES: Course[] = [
  {
    id: 'arc1',
    name: 'Introduction to Computing',
    code: 'IT-101',
    section: 'Previous Semester',
    professor: 'Prof. Alan Turing',
    professorEmail: 'a.turing@school.edu',
    room: 'Online Lecture',
    schedule: 'Completed • AY 2025-2026',
    credits: 3,
    theme: 'bg-indigo-700',
    headerColor: '#4338ca',
    accentColor: 'text-indigo-700',
    grade: '1.50',
  },
  {
    id: 'arc2',
    name: 'Data Structures & Algorithms',
    code: 'IT-201',
    section: 'Previous Semester',
    professor: 'Dr. Grace Hopper',
    professorEmail: 'g.hopper@school.edu',
    room: 'Computer Lab 3',
    schedule: 'Completed • AY 2025-2026',
    credits: 3,
    theme: 'bg-teal-700',
    headerColor: '#0f766e',
    accentColor: 'text-teal-700',
    grade: '1.25',
  },
];

export const INITIAL_ANNOUNCEMENTS: Record<string, Announcement[]> = {
  c1: [
    {
      id: 'a1',
      courseId: 'c1',
      title: 'Web Development Frameworks Overview',
      content: 'This week we will cover modern frontend frameworks. Please review the pre-reading materials on React and Vue.js before Wednesday\'s class.',
      date: 'Oct 12',
      author: 'Engr. Sofia Reyes',
      authorRole: 'Head Instructor',
      isImportant: true,
      attachmentsCount: 2,
      commentsCount: 10,
    },
    {
      id: 'a2',
      courseId: 'c1',
      title: 'Project Repository Setup Guide',
      content: 'All students must set up their GitHub repositories for the semester project. The link to the repository template is in the Materials section.',
      date: 'Sep 28',
      author: 'Engr. Sofia Reyes',
      authorRole: 'Head Instructor',
      isImportant: false,
      attachmentsCount: 1,
      commentsCount: 5,
    },
  ],
  c2: [
    {
      id: 'a3',
      courseId: 'c2',
      title: 'IoT Microcontroller Kit Distribution Notice',
      content: 'ESP32 development boards, sensor kits (DHT11, ultrasonic, PIR), and breadboards can now be claimed from Embedded Systems Lab 201 during lab hours.',
      date: 'Oct 14',
      author: 'Prof. Kevin Ashton',
      authorRole: 'Lead Professor',
      isImportant: true,
      attachmentsCount: 1,
      commentsCount: 9,
    },
    {
      id: 'a4',
      courseId: 'c2',
      title: 'MQTT Broker Protocols and Cloud Dashboard Workshop',
      content: 'We will be connecting our sensor nodes to Adafruit IO and AWS IoT Core. Please register your free developer accounts before Tuesday.',
      date: 'Oct 05',
      author: 'Prof. Kevin Ashton',
      authorRole: 'Lead Professor',
      isImportant: false,
      attachmentsCount: 0,
      commentsCount: 3,
    },
  ],
  c3: [
    {
      id: 'a5',
      courseId: 'c3',
      title: 'Machine Learning Project Datasets Available',
      content: 'The curated datasets for your Supervised Learning Classification Project have been uploaded to the materials repository. Please form groups of 3 and select your target domain (Healthcare, Finance, or Computer Vision) by Friday.',
      date: 'Oct 12',
      author: 'Dr. Geoffrey Hinton',
      authorRole: 'Head Instructor',
      isImportant: true,
      attachmentsCount: 2,
      commentsCount: 14,
    },
    {
      id: 'a6',
      courseId: 'c3',
      title: 'Neural Networks & Deep Learning Setup Guide',
      content: 'Make sure your Google Colab and PyTorch environments are properly configured before our practical coding session next Wednesday.',
      date: 'Sep 28',
      author: 'Dr. Geoffrey Hinton',
      authorRole: 'Head Instructor',
      isImportant: false,
      attachmentsCount: 1,
      commentsCount: 5,
    },
  ],
  c4: [
    {
      id: 'a7',
      courseId: 'c4',
      title: 'UX Usability Heuristic Evaluation Assignment Released',
      content: 'Choose an existing mobile banking or government services application and conduct a 10-point Nielsen Norman Heuristic Evaluation.',
      date: 'Oct 10',
      author: 'Dr. Don Norman',
      authorRole: 'Professor of HCI',
      isImportant: false,
      attachmentsCount: 1,
      commentsCount: 4,
    },
  ],
  c5: [
    {
      id: 'a8',
      courseId: 'c5',
      title: 'System Requirements Specification (SRS) Submission Deadline',
      content: 'Reminder that Draft 1 of your Capstone System Requirements Document is due next Monday. Ensure all UML Use Case diagrams and Data Flow Diagrams follow IEEE standards.',
      date: 'Oct 11',
      author: 'Dr. Larry Constantine',
      authorRole: 'Course Lecturer',
      isImportant: true,
      attachmentsCount: 1,
      commentsCount: 7,
    },
  ],
  c6: [
    {
      id: 'a9',
      courseId: 'c6',
      title: 'REST API & Microservices Integration Architecture',
      content: 'Slides and code starter repositories for FastAPI and Node.js microservice communication are now live in the Materials section.',
      date: 'Oct 13',
      author: 'Engr. Marcus Vance',
      authorRole: 'Lab Instructor',
      isImportant: true,
      attachmentsCount: 1,
      commentsCount: 8,
    },
  ],
  c7: [
    {
      id: 'a10',
      courseId: 'c7',
      title: 'Integrative Project Team Formation',
      content: 'Please form teams of 4 for the semester\'s integrative project. Team leads must submit the group composition form by Friday. The project proposal template is now available in Materials.',
      date: 'Oct 09',
      author: 'Prof. Lena Torres',
      authorRole: 'Course Instructor',
      isImportant: true,
      attachmentsCount: 1,
      commentsCount: 11,
    },
  ],
};

export const INITIAL_MATERIALS: Record<string, Material[]> = {
  c1: [
    {
      id: 'm1',
      courseId: 'c1',
      name: 'Module 2: Responsive Web Design with CSS Grid & Flexbox',
      type: 'ppt',
      category: 'PowerPoint Presentations',
      date: 'Oct 10',
      description: 'Comprehensive slides on CSS Grid, Flexbox layouts, and responsive breakpoint strategies.',
      fileSize: '11.2 MB',
    },
    {
      id: 'm2',
      courseId: 'c1',
      name: 'Lecture Recording: REST APIs & Fetch in JavaScript',
      type: 'video',
      category: 'Lecture Materials',
      date: 'Oct 06',
      description: '75-minute lecture covering async/await, Fetch API, and JSON parsing.',
      fileSize: '290 MB',
    },
    {
      id: 'm3',
      courseId: 'c1',
      name: 'HTML5 & Web Accessibility Standards Reference',
      type: 'pdf',
      category: 'References',
      date: 'Sep 18',
      description: 'WCAG 2.1 guidelines, semantic HTML elements, and ARIA roles quick reference.',
      fileSize: '2.1 MB',
    },
  ],
  c2: [
    {
      id: 'm4',
      courseId: 'c2',
      name: 'ESP32 & Arduino Pinout Architecture Diagram',
      type: 'pdf',
      category: 'References',
      date: 'Sep 15',
      description: 'Full GPIO mapping, ADC channels, I2C, and SPI communication pinouts.',
      fileSize: '3.8 MB',
    },
    {
      id: 'm5',
      courseId: 'c2',
      name: 'Lecture Notes: Wireless Sensor Networks & MQTT Protocol',
      type: 'ppt',
      category: 'PowerPoint Presentations',
      date: 'Oct 04',
      description: 'Publisher-subscriber messaging architecture and low-power WAN topologies.',
      fileSize: '12.1 MB',
    },
  ],
  c3: [
    {
      id: 'm6',
      courseId: 'c3',
      name: 'Module 4: Neural Networks and Backpropagation Slides',
      type: 'ppt',
      category: 'PowerPoint Presentations',
      date: 'Oct 10',
      description: 'Comprehensive slides breaking down gradient descent, activation functions (ReLU, Sigmoid), and loss calculation.',
      fileSize: '16.4 MB',
    },
    {
      id: 'm7',
      courseId: 'c3',
      name: 'Python Scikit-Learn & PyTorch Cheat Sheet',
      type: 'pdf',
      category: 'References',
      date: 'Sep 18',
      description: 'Quick syntax reference for model training, evaluation metrics, and pipeline construction.',
      fileSize: '2.4 MB',
    },
  ],
  c4: [
    {
      id: 'm8',
      courseId: 'c4',
      name: '10 Usability Heuristics by Jakob Nielsen (Illustrated)',
      type: 'pdf',
      category: 'References',
      date: 'Sep 12',
      description: 'Visual reference guide of usability principles and UI design antipatterns.',
      fileSize: '5.1 MB',
    },
    {
      id: 'm9',
      courseId: 'c4',
      name: 'Figma Design System & Wireframing UI Kit',
      type: 'ppt',
      category: 'PowerPoint Presentations',
      date: 'Oct 01',
      description: 'Reusable typography tokens, auto-layout components, and interaction prototypes.',
      fileSize: '22.8 MB',
    },
  ],
  c5: [
    {
      id: 'm10',
      courseId: 'c5',
      name: 'UML 2.5 Diagramming Standards & Templates',
      type: 'doc',
      category: 'Lecture Materials',
      date: 'Sep 25',
      description: 'Templates and conventions for Class Diagrams, Sequence Diagrams, and State Machines.',
      fileSize: '4.2 MB',
    },
    {
      id: 'm11',
      courseId: 'c5',
      name: 'Agile vs Waterfall SDLC Methodology Comparison Guide',
      type: 'pdf',
      category: 'References',
      date: 'Sep 10',
      description: 'In-depth guide on software engineering lifecycles and sprint estimations.',
      fileSize: '1.9 MB',
    },
  ],
  c6: [
    {
      id: 'm12',
      courseId: 'c6',
      name: 'Module 3: Middleware, JWT Auth & WebSockets Integration',
      type: 'ppt',
      category: 'PowerPoint Presentations',
      date: 'Oct 08',
      description: 'Slide deck covering secure authentication tokens and real-time bidirectional sockets.',
      fileSize: '14.5 MB',
    },
    {
      id: 'm13',
      courseId: 'c6',
      name: 'Database Integration Guide: Prisma ORM with PostgreSQL',
      type: 'doc',
      category: 'Other learning resources',
      date: 'Sep 29',
      description: 'Schema migrations, relation modeling, and query optimization patterns.',
      fileSize: '2.7 MB',
    },
  ],
  c7: [
    {
      id: 'm14',
      courseId: 'c7',
      name: 'Integrative Project Proposal Template',
      type: 'doc',
      category: 'Lecture Materials',
      date: 'Oct 01',
      description: 'Official template for the semester integrative project proposal including system overview, scope, and timeline.',
      fileSize: '1.5 MB',
    },
    {
      id: 'm15',
      courseId: 'c7',
      name: 'Full-Stack Technologies Overview Slides',
      type: 'ppt',
      category: 'PowerPoint Presentations',
      date: 'Sep 22',
      description: 'Survey of modern full-stack technologies and integration patterns across web, mobile, and cloud layers.',
      fileSize: '18.3 MB',
    },
  ],
};

export const INITIAL_ACTIVITIES: Record<string, Activity[]> = {
  c1: [
    {
      id: 't1',
      courseId: 'c1',
      title: 'Lab 2: Build a Responsive Portfolio Website',
      category: 'Activities',
      description: 'Create a fully responsive personal portfolio page using HTML5, CSS Grid, and vanilla JavaScript. Must pass WCAG AA color contrast.',
      dueDate: 'Tomorrow, 11:59 PM',
      dueTime: '11:59 PM',
      points: 50,
      status: 'Not Started',
    },
    {
      id: 't2',
      courseId: 'c1',
      title: 'Term Project: Full-Stack Web Application',
      category: 'Projects',
      description: 'Build and deploy a full-stack web app with a REST API backend and dynamic frontend. Submit the GitHub repo link and live demo URL.',
      dueDate: 'Nov 12, 11:59 PM',
      dueTime: '11:59 PM',
      points: 100,
      status: 'In Progress',
    },
    {
      id: 't3',
      courseId: 'c1',
      title: 'Quiz 1: HTTP Methods & Web Architecture',
      category: 'Quizzes',
      description: 'Multiple choice on HTTP verbs, status codes, REST principles, and client-server architecture.',
      dueDate: 'Oct 02 (Closed)',
      dueTime: '10:00 AM',
      points: 30,
      status: 'Submitted',
      submittedAt: 'Oct 01, 9:20 PM',
    },
  ],
  c2: [
    {
      id: 't4',
      courseId: 'c2',
      title: 'Lab Exercise: Smart Environmental Monitoring with ESP32',
      category: 'Activities',
      description: 'Connect DHT11 temperature/humidity sensor to ESP32 and publish real-time telemetry over MQTT to a cloud dashboard.',
      dueDate: 'Oct 18, 11:59 PM',
      dueTime: '11:59 PM',
      points: 45,
      status: 'Not Started',
    },
    {
      id: 't5',
      courseId: 'c2',
      title: 'IoT Prototype Design Proposal',
      category: 'Projects',
      description: 'Submit a 3-page proposal specifying hardware architecture, power budget, and cloud connectivity for your prototype.',
      dueDate: 'Nov 05, 5:00 PM',
      dueTime: '5:00 PM',
      points: 100,
      status: 'In Progress',
    },
  ],
  c3: [
    {
      id: 't6',
      courseId: 'c3',
      title: 'Lab 4: Building a Decision Tree Classifier in Python',
      category: 'Activities',
      description: 'Implement a decision tree model on the Iris/Wine dataset from scratch and using Scikit-Learn. Evaluate precision, recall, and F1-score.',
      dueDate: 'Oct 18, 11:59 PM',
      dueTime: '11:59 PM',
      points: 50,
      status: 'Not Started',
    },
    {
      id: 't7',
      courseId: 'c3',
      title: 'Term Project: Convolutional Neural Network Image Classifier',
      category: 'Projects',
      description: 'Train a CNN model achieving >85% validation accuracy on a chosen multi-class image classification dataset. Submit notebook and report.',
      dueDate: 'Nov 12, 11:59 PM',
      dueTime: '11:59 PM',
      points: 100,
      status: 'In Progress',
    },
    {
      id: 't8',
      courseId: 'c3',
      title: 'Quiz 2: Search Algorithms & Heuristics (A*, Minimax)',
      category: 'Quizzes',
      description: 'Multiple choice and pseudocode analysis on informed search algorithms.',
      dueDate: 'Oct 02 (Closed)',
      dueTime: '10:00 AM',
      points: 30,
      status: 'Submitted',
      submittedAt: 'Oct 01, 9:20 PM',
    },
  ],
  c4: [
    {
      id: 't9',
      courseId: 'c4',
      title: 'Interactive High-Fidelity Prototype in Figma',
      category: 'Projects',
      description: 'Design an accessible, responsive mobile UI prototype incorporating component variants, animations, and WCAG AA contrast compliance.',
      dueDate: 'Nov 18, 11:59 PM',
      dueTime: '11:59 PM',
      points: 100,
      status: 'In Progress',
    },
    {
      id: 't10',
      courseId: 'c4',
      title: 'Heuristic Evaluation Report',
      category: 'Activities',
      description: 'Identify 5 severe usability flaws in a nominated website and write actionable redesign recommendations.',
      dueDate: 'Oct 15, 11:59 PM',
      dueTime: '11:59 PM',
      points: 35,
      status: 'Not Started',
    },
  ],
  c5: [
    {
      id: 't11',
      courseId: 'c5',
      title: 'System Requirements Specification (SRS) Draft 1',
      category: 'Projects',
      description: 'Comprehensive functional and non-functional requirements document including context diagram and complete data dictionary.',
      dueDate: 'Oct 20, 11:59 PM',
      dueTime: '11:59 PM',
      points: 100,
      status: 'In Progress',
    },
    {
      id: 't12',
      courseId: 'c5',
      title: 'UML Sequence Diagram Exercise',
      category: 'Activities',
      description: 'Model the user authentication and checkout transaction flow for an online booking platform.',
      dueDate: 'Oct 08 (Closed)',
      dueTime: '11:59 PM',
      points: 25,
      status: 'Submitted',
      submittedAt: 'Oct 07, 7:45 PM',
    },
  ],
  c6: [
    {
      id: 't13',
      courseId: 'c6',
      title: 'Hands-on Lab: Secure JWT Authentication Microservice',
      category: 'Activities',
      description: 'Build an Express/Node.js auth service with access/refresh token rotation and bcrypt password hashing.',
      dueDate: 'Oct 17, 11:59 PM',
      dueTime: '11:59 PM',
      points: 40,
      status: 'Not Started',
    },
    {
      id: 't14',
      courseId: 'c6',
      title: 'Integration Quiz: WebHooks & Third-Party APIs',
      category: 'Quizzes',
      description: 'Timed assessment on payload validation, HMAC signatures, and rate limiting strategies.',
      dueDate: 'Oct 24, 2:00 PM',
      dueTime: '2:00 PM',
      points: 30,
      status: 'Not Started',
    },
  ],
  c7: [
    {
      id: 't15',
      courseId: 'c7',
      title: 'Integrative Project Proposal Submission',
      category: 'Projects',
      description: 'Submit the signed team composition form and 3-page project proposal covering system architecture, tech stack, and Gantt chart.',
      dueDate: 'Oct 22, 5:00 PM',
      dueTime: '5:00 PM',
      points: 100,
      status: 'In Progress',
    },
    {
      id: 't16',
      courseId: 'c7',
      title: 'Technology Stack Analysis Activity',
      category: 'Activities',
      description: 'Compare 3 different full-stack technology combinations (MERN, LAMP, Django+React) and justify the best choice for your project.',
      dueDate: 'Oct 10 (Closed)',
      dueTime: '11:59 PM',
      points: 25,
      status: 'Submitted',
      submittedAt: 'Oct 09, 10:30 PM',
    },
  ],
};

export const CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'ce1',
    title: 'Web Systems and Technologies Lecture',
    courseId: 'c1',
    courseName: 'Web Systems and Technologies',
    type: 'lecture',
    day: 'Monday',
    dateStr: 'Mon, Oct 13',
    time: '7:30 AM - 9:00 AM',
    color: 'bg-cyan-600',
  },
  {
    id: 'ce2',
    title: 'Artificial Intelligence Lecture & Colab Lab',
    courseId: 'c3',
    courseName: 'Artificial Intelligence',
    type: 'lecture',
    day: 'Monday',
    dateStr: 'Mon, Oct 13',
    time: '9:00 AM - 10:30 AM',
    color: 'bg-blue-600',
  },
  {
    id: 'ce3',
    title: 'System Analysis and Design Lecture',
    courseId: 'c5',
    courseName: 'System Analysis and Design',
    type: 'lecture',
    day: 'Monday',
    dateStr: 'Mon, Oct 13',
    time: '1:00 PM - 2:30 PM',
    color: 'bg-orange-600',
  },
  {
    id: 'ce4',
    title: 'Internet of Things (IoT) Hardware Lab',
    courseId: 'c2',
    courseName: 'Internet of Things (IoT)',
    type: 'lecture',
    day: 'Tuesday',
    dateStr: 'Tue, Oct 14',
    time: '10:00 AM - 12:00 PM',
    color: 'bg-emerald-700',
  },
  {
    id: 'ce5',
    title: 'System Integration and Architecture I Lab',
    courseId: 'c6',
    courseName: 'System Integration and Architecture I',
    type: 'lecture',
    day: 'Tuesday',
    dateStr: 'Tue, Oct 14',
    time: '1:30 PM - 3:30 PM',
    color: 'bg-purple-700',
  },
  {
    id: 'ce6',
    title: 'Integrative Programming Technologies Session',
    courseId: 'c7',
    courseName: 'Integrative Programming and Technologies I',
    type: 'lecture',
    day: 'Tuesday',
    dateStr: 'Tue, Oct 14',
    time: '3:30 PM - 5:30 PM',
    color: 'bg-violet-600',
  },
  {
    id: 'ce7',
    title: 'Web Systems Portfolio Lab DUE',
    courseId: 'c1',
    courseName: 'Web Systems and Technologies',
    type: 'deadline',
    day: 'Wednesday',
    dateStr: 'Wed, Oct 15',
    time: '11:59 PM',
    color: 'bg-cyan-600',
  },
  {
    id: 'ce8',
    title: 'IoT Telemetry Exercise DUE',
    courseId: 'c2',
    courseName: 'Internet of Things (IoT)',
    type: 'deadline',
    day: 'Thursday',
    dateStr: 'Thu, Oct 16',
    time: '11:59 PM',
    color: 'bg-emerald-700',
  },
  {
    id: 'ce9',
    title: 'Human-Computer Interaction 1 UX Studio',
    courseId: 'c4',
    courseName: 'Human-Computer Interaction 1',
    type: 'lecture',
    day: 'Friday',
    dateStr: 'Fri, Oct 17',
    time: '9:00 AM - 12:00 PM',
    color: 'bg-rose-600',
  },
];
